# Generated by Django 5.1 on 2025-03-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_discount_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='contant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=5000)),
                ('password', models.CharField(max_length=90)),
            ],
        ),
    ]
