# Generated by Django 5.1 on 2025-03-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contant',
            new_name='Contants',
        ),
    ]
