# Generated by Django 5.1 on 2025-04-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contants',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contants',
            old_name='password',
            new_name='F_name',
        ),
        migrations.AddField(
            model_name='contants',
            name='L_name',
            field=models.CharField(default='a', max_length=90),
        ),
        migrations.AddField(
            model_name='contants',
            name='Message',
            field=models.CharField(default='a', max_length=90),
        ),
        migrations.AddField(
            model_name='contants',
            name='SubjectC',
            field=models.CharField(default='a', max_length=90),
        ),
    ]
