# Generated by Django 5.1 on 2025-04-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_email_contants_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemsjson', models.CharField(max_length=5000)),
                ('product_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
                ('Zipcode', models.CharField(max_length=90)),
                ('amount', models.IntegerField(default=0)),
                ('coupon', models.CharField(default='', max_length=90)),
            ],
        ),
    ]
