# Generated by Django 5.1 on 2025-04-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contants',
            new_name='Form',
        ),
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
